### PR TITLE
corrected link to coding style page

### PR DESCRIPTION
**Pull request by shiftkey**

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM

**Comment by Priya91** [comment]
The link is changed again.

**Comment by NickCraver** [comment]
Should be closed out - no longer needed.

**Comment by shiftkey** [comment]
@NickCraver thanks for reminding me - this no longer lives in the wiki.

I'll leave it up to the others whether they want to take this in.

**Comment by shiftkey** [comment]
:fire:

**Pull request closed without merging**
