### PR TITLE
Updating readme with the missing nocopyright flag

### PR DESCRIPTION
**Pull request by aaronpowell**

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
LGTM

**Comment by khellang** [comment]
Shouldn't README.md match what's in [Program.cs](https://github.com/dotnet/codeformatter/blob/master/src/CodeFormatter/Program.cs#L27-L33)?

> CodeFormatter <project or solution> [<rule types>] [/file:<filename>] [/nocopyright] [/c:<config1,config2> [/copyright:file]
>     <rule types> - Rule types to use in addition to the default ones.
>                    Use ConvertTests to convert MSTest tests to xUnit.
>     <filename>   - Only apply changes to files with specified name.
>     <configs>    - Additional preprocessor configurations the formatter
>                    should run under.
>     <copyright>  - Specifies file containing copyright header.

**Comment by aaronpowell** [comment]
Yeah I realised that later yesterday when I was digging in the code, I just hadn't updated my PR :stuck_out_tongue:

**Comment by jaredpar** [comment]
@aaronpowell can you please sign the CLA for .NET Foundation Contribution? 

https://cla2.dotnetfoundation.org/

**Comment by aaronpowell** [comment]
@jaredpar - Seems that DocuSign have broken my account so there will be a delay on me signing my CLA while they try and resolve my account issues

**Pull request merged**
