### PR TITLE
Add new rule to convert Test Assert.True or False with redundant conditi...

### PR DESCRIPTION
**Pull request by YingP99**
Add new rule to convert Test Assert.True or False with redundant condition.

### CODE REVIEW

**Comment by ellismg** [comment]
Can you redo this commit as yourself?  Set core.name and core.e-mail to your information and then git commit --amend --reset-author.  Then force push your branch with git push origin +assertrule:assertrule.

**Comment by YingP99** [comment]
@ellismg Done!

**Comment by jaredpar** [comment]
I'm not sure this rule is appropriate for the code formatter for a couple of reasons:

- It is not a part of our coding guidelines.  All rules today which aren't a part of the guidelines are being moved out and into separate projects.
- This is not a rule that can be run safely on a code base.  At least not without introducing semantic analysis into the equation.  The translation between `Assert.True(x ==y)` to `Assert.Equals(x, y)` is not always correct.  It confuses reference and value equality without checking to see if the type in question does reference equality.

**Comment by YingP99** [comment]
@jaredpar you are right. This is not meant for product code, but for converting some Assert in xUnit tests, and I don't want to get it complicated by involving semantic analysis. I put here because other test related rules such as convert MSTest to xUnit tests are also in this project.
Where is or will be another project for non-coding guideline rules?

**Comment by jaredpar** [comment]
@YingP99 

I think this repo is the right place for such conversion tools, we just need to create a different application for it.  I'm actually doing that right now for the rest of the xUnit conversion code.  I'm not sure if this rule should or shouldn't go into that one.

**Comment by YingP99** [comment]
@jaredpar  It definitely should go with the xUnit test convert rule. Can I merge this pull request first, then you move it? I'll be on vacation next week (leave on Sunday), so I'd like to get it in today.

**Comment by jaredpar** [comment]
@YingP99 sure, that's fine.  I can just pull it into my branch later today.

**Comment by YingP99** [comment]
@jaredpar merged. Please move it to another project.
If you have time and agree with @ellismg, please address his comments as well (I'm not disagree with him). Thx.

**Pull request merged**
